user:
  #username 学号或者工号
  username: '20202329'
  #tellphone 电话号码
  tellphone: '17581727156'
  #address 地址，定位信息
  address: 中国四川省德阳市旌阳区工农街道G350(嘉陵江西路)
  #email 接受通知消息的邮箱
  email: 1451684500@qq.com
  #lon 当前位置经度，可以访问

http://zuobiao.ay800.com/s/27/index.php获取
  lon: '104.38275580512153'
  #lat 当前位置纬度
  lat: '31.087701822916667'
  #school 学校全称
  school: 四川建筑职业技术学院
#今日校园相关配置
cpdaily:
  #表单组默认选项配置
  defaults:
    #表单默认选项配置，按顺序，注意，只有标必填项的才处理，不会配置就执行

generate.py
    - default:
        title: 今日所在位置
        type: 1
        value: 四川省/德阳市/旌阳区/四川建院
    - default:
        title: 最近14天内你是否离开过目前所在地
        type: 2
        value: 否       - default:
        title: 上一题如果选是，请填写去了哪里（填写规范XXXX省XXXX市）
        type: 1
        value: 否
    - default:
        title: 最近14天内是否接触过疑似或确诊患者或密切接触者
        type: 2
        value: 否
    - default:
        title: 最近14天内是否接触过来自重点疫区人员或密切接触者
        type: 2
        value: 否
    - default:
        title: 是否被医院确定为疑似患新型冠状病毒肺炎
        type: 2
        value: 否
    - default:
        title: 是否被相关机构实施医学隔离
        type: 2
        value: 否
    - default:
        title: 昨日晚上实测体温
        type: 2
        value: 36.1-36.9℃（正常）
    - default:
        title: 今日早上实测体温
        type: 2
        value: 36.1-36.9℃（正常）
    - default:
        title: 今日中午实测体温
        type: 2
        value: 36.1-36.9℃（正常）
    - default:
        title: 本人当前是否有发热、乏力、干咳、呼吸困难等症状
        type: 2
        value: 否
    - default:
        title: 共同生活的家人当前是否有发热、乏力、干咳、呼吸困难等症状
        type: 2
        value: 否
    - default:
        title: 当前所居住小区（或村庄）是否有确诊病例
        type: 2
        value: 否
    - default:
        title: 疫情发生以来是否按要求在家活动，没有随意外出
        type: 2
        value: 是
    - default:
        title: 其他与疫情相关情况请说明（没有就填无）
        type: 1
        value: 无
    - default:
        title: 本人是否承诺以上所填报的全部内容均属实、准确，不存在任何隐瞒与不实的情况，更无遗漏之处。
        type: 1
        value: 是
